GroupSocialAutomation.OPTION_DEFAULTS = {
	global = { -- this table is required (or at least a table of a specific key - see AceDB @ L294)
		settings = {
			general = {
				userSpokenLangs = {
					enUS = true,
					deDE = false,
					frFR = false,
					koKR = false,
					zhCN = false,
					zhTW = false,
					esES = false,
					esMX = false,
					ruRU = false,
					ptBR = false,
					itIT = false,
				},
				groupTypesToGreet = {
					lfd = true,
					premade = true,
					premade_raids = true,
					lfr = true
				},
				greet_joining_player_with_name = true,

				lang_independent_greetings = "Hi\nHey\n\\o\no/",
				lang_independent_farewells = "Bye\nC U\n\\o\no/",

				-- translations generated with chatgpt - you are welcome to help with accurate translations

				--[[
				-- GREETINGS
				]]
				setting_enUS_greetings = "Greetings!\nHello!",
				setting_deDE_greetings = "Grüße!\nHallo!",
				setting_koKR_greetings = "안녕하세요\n인사\n안녕하세요",
				setting_frFR_greetings = "Salut\nSalutations\nBonjour",
				setting_zhCN_greetings = "你好\n问候\n你好",
				setting_zhTW_greetings = "你好\n問候\n你好",
				setting_esES_greetings = "Hola\nSaludos\nHola",
				setting_esMX_greetings = "Hola\nSaludos\nHola",
				setting_ruRU_greetings = "Привет\nПриветствие\nЗдравствуйте",
				setting_ptBR_greetings = "Oi\nSaudações\nOlá",
				setting_itIT_greetings = "Ciao\nSaluti\nCiao",

				setting_enUS_greetings_morning = "Good morning",
				setting_deDE_greetings_morning = "Guten Morgen",
				setting_koKR_greetings_morning = "좋은 아침",
				setting_frFR_greetings_morning = "Bonjour",
				setting_zhCN_greetings_morning = "早上好",
				setting_zhTW_greetings_morning = "早安",
				setting_esES_greetings_morning = "Buenos días",
				setting_esMX_greetings_morning = "Buenos días",
				setting_ruRU_greetings_morning = "Доброе утро",
				setting_ptBR_greetings_morning = "Bom dia",
				setting_itIT_greetings_morning = "Buongiorno",

				setting_enUS_greetings_afternoon = "Good afternoon",
				setting_deDE_greetings_afternoon = "Guten Nachmittag",
				setting_koKR_greetings_afternoon = "좋은 오후",
				setting_frFR_greetings_afternoon = "Bon après-midi",
				setting_zhCN_greetings_afternoon = "下午好",
				setting_zhTW_greetings_afternoon = "午安",
				setting_esES_greetings_afternoon = "Buenas tardes",
				setting_esMX_greetings_afternoon = "Buenas tardes",
				setting_ruRU_greetings_afternoon = "Добрый день",
				setting_ptBR_greetings_afternoon = "Boa tarde",
				setting_itIT_greetings_afternoon = "Buon pomeriggio",

				setting_enUS_greetings_evening = "Good evening",
				setting_deDE_greetings_evening = "Guten Abend",
				setting_koKR_greetings_evening = "좋은 저녁",
				setting_frFR_greetings_evening = "Bonsoir",
				setting_zhCN_greetings_evening = "晚上好",
				setting_zhTW_greetings_evening = "晚安",
				setting_esES_greetings_evening = "Buenas noches",
				setting_esMX_greetings_evening = "Buenas noches",
				setting_ruRU_greetings_evening = "Добрый вечер",
				setting_ptBR_greetings_evening = "Boa noite",
				setting_itIT_greetings_evening = "Buona sera",

				setting_enUS_greetings_night = "Good night",
				setting_deDE_greetings_night = "Hallo ihr Nachteulen!",
				setting_koKR_greetings_night = "안녕히 주무세요",
				setting_frFR_greetings_night = "Bonne nuit",
				setting_zhCN_greetings_night = "晚安",
				setting_zhTW_greetings_night = "晚安",
				setting_esES_greetings_night = "Buenas noches",
				setting_esMX_greetings_night = "Buenas noches",
				setting_ruRU_greetings_night = "Спокойной ночи",
				setting_ptBR_greetings_night = "Boa noite",
				setting_itIT_greetings_night = "Buona notte",

				setting_enUS_greetings_midday = "Good midday",
				setting_deDE_greetings_midday = "Guten Mittag",
				setting_koKR_greetings_midday = "좋은 한낮",
				setting_frFR_greetings_midday = "Bonjour",
				setting_zhCN_greetings_midday = "午安",
				setting_zhTW_greetings_midday = "午安",
				setting_esES_greetings_midday = "Buen mediodía",
				setting_esMX_greetings_midday = "Buen mediodía",
				setting_ruRU_greetings_midday = "Добрый день",
				setting_ptBR_greetings_midday = "Bom meio-dia",
				setting_itIT_greetings_midday = "Buon mezzogiorno",

				--[[
				-- FAREWELLS
				]]
				setting_enUS_farewells = "Thanks & good bye!\nThanks & bye!\nThanks & farewell!\nThanks & bye bye!",
				setting_deDE_farewells = "Danke & auf wiedersehen!\nDanke & tschüss!\nDanke & bye!\nDanke & bye bye!",
				setting_koKR_farewells = "안녕히 가세요\n안녕\n안녕히 계세요",
				setting_frFR_farewells = "Au revoir\nAdieu\nFarewell",
				setting_zhCN_farewells = "再见\n再会\n告别",
				setting_zhTW_farewells = "再見\n再會\n告別",
				setting_esES_farewells = "Adiós\nHasta luego\nHasta la vista",
				setting_esMX_farewells = "Adiós\nHasta luego\nHasta la vista",
				setting_ruRU_farewells = "До свидания\nПрощай\nДо встречи",
				setting_ptBR_farewells = "Adeus\nTchau\nAté logo",
				setting_itIT_farewells = "Arrivederci\nAddio\nAddio",

				setting_enUS_farewells_morning = "Good morning and goodbye",
				setting_deDE_farewells_morning = "Angenehmen Morgen noch!",
				setting_koKR_farewells_morning = "좋은 아침, 안녕히 가세요",
				setting_frFR_farewells_morning = "Bonjour et au revoir",
				setting_zhCN_farewells_morning = "早上好，再见",
				setting_zhTW_farewells_morning = "早安，再見",
				setting_esES_farewells_morning = "Buenos días y adiós",
				setting_esMX_farewells_morning = "Buenos días y adiós",
				setting_ruRU_farewells_morning = "Доброе утро и до свидания",
				setting_ptBR_farewells_morning = "Bom dia e adeus",
				setting_itIT_farewells_morning = "Buongiorno e arrivederci",

				setting_enUS_farewells_afternoon = "Good afternoon and goodbye",
				setting_deDE_farewells_afternoon = "Schönen Tag noch!",
				setting_koKR_farewells_afternoon = "좋은 오후, 안녕히 가세요",
				setting_frFR_farewells_afternoon = "Bon après-midi et au revoir",
				setting_zhCN_farewells_afternoon = "下午好，再见",
				setting_zhTW_farewells_afternoon = "午安，再見",
				setting_esES_farewells_afternoon = "Buenas tardes y adiós",
				setting_esMX_farewells_afternoon = "Buenas tardes y adiós",
				setting_ruRU_farewells_afternoon = "Добрый день и до свидания",
				setting_ptBR_farewells_afternoon = "Boa tarde e adeus",
				setting_itIT_farewells_afternoon = "Buon pomeriggio e arrivederci",

				setting_enUS_farewells_evening = "Good evening and goodbye",
				setting_deDE_farewells_evening = "Schönen Abend noch!",
				setting_koKR_farewells_evening = "좋은 저녁, 안녕히 가세요",
				setting_frFR_farewells_evening = "Bonsoir et au revoir",
				setting_zhCN_farewells_evening = "晚上好，再见",
				setting_zhTW_farewells_evening = "晚安，再見",
				setting_esES_farewells_evening = "Buenas noches y adiós",
				setting_esMX_farewells_evening = "Buenas noches y adiós",
				setting_ruRU_farewells_evening = "Добрый вечер и до свидания",
				setting_ptBR_farewells_evening = "Boa noite e adeus",
				setting_itIT_farewells_evening = "Buona sera e arrivederci",

				setting_enUS_farewells_night = "Good night and goodbye",
				setting_deDE_farewells_night = "Gute Nacht oder einen schönen Abend!",
				setting_koKR_farewells_night = "안녕히 주무세요, 안녕히 가세요",
				setting_frFR_farewells_night = "Bonne nuit et au revoir",
				setting_zhCN_farewells_night = "晚安，再见",
				setting_zhTW_farewells_night = "晚安，再見",
				setting_esES_farewells_night = "Buenas noches y adiós",
				setting_esMX_farewells_night = "Buenas noches y adiós",
				setting_ruRU_farewells_night = "Спокойной ночи и до свидания",
				setting_ptBR_farewells_night = "Boa noite e adeus",
				setting_itIT_farewells_night = "Buona notte e arrivederci",

				setting_enUS_farewells_midday = "Good midday and goodbye",
				setting_deDE_farewells_midday = "Schönen Tag noch!",
				setting_koKR_farewells_midday = "좋은 한낮, 안녕히 가세요",
				setting_frFR_farewells_midday = "Bonjour et au revoir",
				setting_zhCN_farewells_midday = "午安，再见",
				setting_zhTW_farewells_midday = "午安，再見",
				setting_esES_farewells_midday = "Buen mediodía y adiós",
				setting_esMX_farewells_midday = "Buen mediodía y adiós",
				setting_ruRU_farewells_midday = "Добрый день и до свидания",
				setting_ptBR_farewells_midday = "Bom meio-dia e adeus",
				setting_itIT_farewells_midday = "Buon mezzogiorno e arrivederci",

				--[[ ======================================================= ]]

				setting_enUS_allow_timeframe_independent = true,
				setting_deDE_allow_timeframe_independent = true,
				setting_koKR_allow_timeframe_independent = true,
				setting_frFR_allow_timeframe_independent = true,
				setting_zhCN_allow_timeframe_independent = true,
				setting_zhTW_allow_timeframe_independent = true,
				setting_esES_allow_timeframe_independent = true,
				setting_esMX_allow_timeframe_independent = true,
				setting_ruRU_allow_timeframe_independent = true,
				setting_ptBR_allow_timeframe_independent = true,
				setting_itIT_allow_timeframe_independent = true,

				setting_enUS_allow_timeframe_dependent = true,
				setting_deDE_allow_timeframe_dependent = true,
				setting_koKR_allow_timeframe_dependent = true,
				setting_frFR_allow_timeframe_dependent = true,
				setting_zhCN_allow_timeframe_dependent = true,
				setting_zhTW_allow_timeframe_dependent = true,
				setting_esES_allow_timeframe_dependent = true,
				setting_esMX_allow_timeframe_dependent = true,
				setting_ruRU_allow_timeframe_dependent = true,
				setting_ptBR_allow_timeframe_dependent = true,
				setting_itIT_allow_timeframe_dependent = true,
			},
			lfd = {
				wait_until_all_connected = true,
				wait_time_after_join = 4,
				congratulate_on_level_up = true,
			}
		},
	}
}